In [1]:
from ast import literal_eval
from collections import defaultdict

import pandas as pd
import os
import json
from sklearn.model_selection import train_test_split

In [2]:
pd.read_csv('../data/processed/positive_data_community_descriptions.csv', nrows=2, index_col=0)

,community_name,community_description,comment_id,description,extracted_rules
0,10_0,I live in a prison called My Parents Basement ...,"[13586358, 5430356, 1324064, 501042, 467224, 4...",I live in a prison called My Parents Basement ...,"\n{""Rules"": [{""Number"": ""1"", ""Description"": ""D..."
1,12in12,A place to post the list of games you hope to ...,"[14769620, 14672881, 14541371, 14541361, 13634...",A place to post the list of games you hope to ...,"\n{""Rules"": [{""Number"": ""1"", ""Description"": ""D..."

In [3]:
pd.read_csv('../data/processed/positive_data_with_extracted_rules.csv', nrows=2, index_col=0)

,community_name,community_id,comment_id,content,community_description,language,exrtacted_rules
0,saas,557426,13322168,I would look into queues and a background task...,Software As a Service Companies — The Future O...,37,"\n{""Rules"": []}\n"
1,saas,557426,12184725,Currently I have a documentation page that poi...,Software As a Service Companies — The Future O...,37,"\n{""Rules"": []}\n"

In [4]:
df1 = pd.read_csv('../data/processed/df_rule_number_mapping_without_error.csv', index_col=0)

In [5]:
df2 = pd.read_csv('../data/processed/df_no_rule_exact_match_no_error.csv', index_col=0)

In [6]:
set(df1.columns).difference(set(df2.columns))

{'rule_numbers'}

In [7]:
set(df2.columns).difference(set(df1.columns))

{'Unnamed: 0.1'}

In [8]:
df1.rule_numbers.unique()

array(["['2']", "['6']", "['1']", "['5']", "['1', '2']", "['4']",
       "['1', '3']", "['3']", "['9']", "['1', '5']", "['2', '3']",
       "['7']", "['3', '2']", "['8']", "['1', '9']", "['1', '6']",
       "['12']", "['2', '1', '3']", "['4', '3', '7']", "['2', '5']",
       "['2', '3', '5']", "['3', '5']", "['3', '4']", "['3', '7']",
       "['2', '1']", "['1', '2', '4']", "['2', '2']", "['2', '4']",
       "['1', '4']", "['5', '7']", "['1', '1']", "['3', '6']",
       "['7', '8']", "['3', '4', '6']", "['1', '8']", "['2', '7']",
       "['1', '2', '3', '4', '5']", "['5', '7', '8']", "['8', '7']",
       "['1', '4', '7']", "['3', '1']", "['1', '7']", "['6', '3']",
       "['1', '3', '4']", "['4', '7']", "['8', '3']", "['4', '5']",
       "['3', '3']", "['1', '5', '6']", "['2', '1', '2']", "['5', '6']",
       "['8', '6']", "['6', '5']", "['8', '2', '2', '2']",
       "['6', '2', '3']", "['3', '8']", "['8', '1']", "['1', '3', '5']",
       "['5', '1']", "['10']", "['1', '2', '4', '5']", "['1', '1', '8']",
       "['1', '4', '5', '6']", "['1', '4', '5', '10']",
       "['1', '4', '10']", "['5', '10']", "['3', '5', '6']",
       "['1', '3', '5', '6']", "['2', '3', '6']", "['1', '11']", "['11']",
       "['1', '4', '6']", "['1', '2', '3']"], dtype=object)

In [9]:
df1.rule_numbers = df1.rule_numbers.apply(literal_eval)

In [10]:
df2.mapped_reasons = df2.mapped_reasons.apply(literal_eval)

In [11]:
df2['rule_numbers'] = df2.mapped_reasons

In [12]:
df = pd.concat([df1, df2], axis=0, ignore_index=True)

In [13]:
df = df[df.rule_numbers.apply(len)==1].copy()

In [14]:
df['rule']=df.rule_numbers.apply(lambda x:x[0])

In [15]:
df.head()

,Unnamed: 0,instance,community_name,community_id,comment_id,content,community_description,comment_published,comment_removed,reason,language,exrtacted_rules,extracted_rules_json,rule_numbers,mapped_reasons,is_mass_removed,Unnamed: 0.1,rule
0,6,ani.social,meta,34,2243845,🤡,Welcome to the AniSocial Lemmy community!\n\nT...,2023-11-07T00:18:02.163076Z,2023-11-07T00:33:39.337517Z,"Breaks community rule: ""2. Be kind and respect...",37,"\n{""Rules"": [{""Number"": ""1"", ""Description"": ""A...",{'rules': {1: 'All posts must be related to th...,[2],['Be kind and respectful to one another.'],0,NaN,2
1,7,ani.social,meta,34,2243457,All three regarded instances have admins that ...,Welcome to the AniSocial Lemmy community!\n\nT...,2023-11-06T23:54:25.185884Z,2023-11-07T00:33:57.229908Z,"Breaks community rule: ""2. Be kind and respect...",37,"\n{""Rules"": [{""Number"": ""1"", ""Description"": ""A...",{'rules': {1: 'All posts must be related to th...,[2],['Be kind and respectful to one another.'],0,NaN,2
2,8,ani.social,meta,34,2243847,🤡,Welcome to the AniSocial Lemmy community!\n\nT...,2023-11-07T00:18:07.077425Z,2023-11-07T00:34:05.931024Z,"Breaks community rule: ""2. Be kind and respect...",37,"\n{""Rules"": [{""Number"": ""1"", ""Description"": ""A...",{'rules': {1: 'All posts must be related to th...,[2],['Be kind and respectful to one another.'],0,NaN,2
3,9,ani.social,meta,34,2243842,Can you please just leave me the fuck alone yo...,Welcome to the AniSocial Lemmy community!\n\nT...,2023-11-07T00:17:23.467802Z,2023-11-07T00:36:37.467424Z,"Breaks community rule: ""2. Be kind and respect...",37,"\n{""Rules"": [{""Number"": ""1"", ""Description"": ""A...",{'rules': {1: 'All posts must be related to th...,[2],['Be kind and respectful to one another.'],0,NaN,2
4,20,ani.social,thiccmoe,36835,4939804,Artist obsession with thigh gaps is ridiculous.,Anime characters who have those not-straight l...,2024-06-02T22:18:32.704784Z,2024-06-02T22:58:25.247207Z,Rule 6: No shitting on the art/artist or fans ...,37,"\n{""Rules"": [{""Number"": ""1"", ""Description"": ""P...",{'rules': {1: 'Posts must feature thiccmoe. Th...,[6],"['Positivity only. No shitting on the art, the...",0,NaN,6

In [16]:
df[['instance', 'community_name', 'community_id',
       'comment_id', 'content', 'community_description', 'comment_published',
       'comment_removed', 'reason', 'language', 
       'extracted_rules_json', 'mapped_reasons',
       'is_mass_removed', 'rule']]

,instance,community_name,community_id,comment_id,content,community_description,comment_published,comment_removed,reason,language,extracted_rules_json,mapped_reasons,is_mass_removed,rule
0,ani.social,meta,34,2243845,🤡,Welcome to the AniSocial Lemmy community!\n\nT...,2023-11-07T00:18:02.163076Z,2023-11-07T00:33:39.337517Z,"Breaks community rule: ""2. Be kind and respect...",37,{'rules': {1: 'All posts must be related to th...,['Be kind and respectful to one another.'],0,2
1,ani.social,meta,34,2243457,All three regarded instances have admins that ...,Welcome to the AniSocial Lemmy community!\n\nT...,2023-11-06T23:54:25.185884Z,2023-11-07T00:33:57.229908Z,"Breaks community rule: ""2. Be kind and respect...",37,{'rules': {1: 'All posts must be related to th...,['Be kind and respectful to one another.'],0,2
2,ani.social,meta,34,2243847,🤡,Welcome to the AniSocial Lemmy community!\n\nT...,2023-11-07T00:18:07.077425Z,2023-11-07T00:34:05.931024Z,"Breaks community rule: ""2. Be kind and respect...",37,{'rules': {1: 'All posts must be related to th...,['Be kind and respectful to one another.'],0,2
3,ani.social,meta,34,2243842,Can you please just leave me the fuck alone yo...,Welcome to the AniSocial Lemmy community!\n\nT...,2023-11-07T00:17:23.467802Z,2023-11-07T00:36:37.467424Z,"Breaks community rule: ""2. Be kind and respect...",37,{'rules': {1: 'All posts must be related to th...,['Be kind and respectful to one another.'],0,2
4,ani.social,thiccmoe,36835,4939804,Artist obsession with thigh gaps is ridiculous.,Anime characters who have those not-straight l...,2024-06-02T22:18:32.704784Z,2024-06-02T22:58:25.247207Z,Rule 6: No shitting on the art/artist or fans ...,37,{'rules': {1: 'Posts must feature thiccmoe. Th...,"['Positivity only. No shitting on the art, the...",0,6
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18613,ttrpg.network,rpg,4,4847780,![zenz](https://www.hexbear.net/pictrs/image/c...,This community is for meaningful discussions o...,2024-01-31T21:53:33.711022Z,2024-02-02T00:14:37.573525Z,Flamewar,37,{'rules': {1: 'Do not distribute pirate conten...,[2],0,2
18614,ttrpg.network,rpg,4,4870219,"Oh yeah, Iraq was just a lil oopsie that kille...",This community is for meaningful discussions o...,2024-02-01T22:31:51.573362Z,2024-02-02T00:15:53.096714Z,Flamewar,37,{'rules': {1: 'Do not distribute pirate conten...,[2],0,2
18615,ttrpg.network,rpg,4,4867615,你个狗屁 白痴 肏你妈的屄 你二大爷的 蠢豬 你应该为自己感到羞耻 笨蛋Simpleton ...,This community is for meaningful discussions o...,2024-02-01T20:00:05.818559Z,2024-02-02T00:15:58.308254Z,Flamewar,37,{'rules': {1: 'Do not distribute pirate conten...,[2],0,2
18616,ttrpg.network,rpg,4,4867134,How much of a racist moron do you need to be t...,This community is for meaningful discussions o...,2024-02-01T19:33:08.242093Z,2024-02-02T00:16:08.709085Z,Flamewar,37,{'rules': {1: 'Do not distribute pirate conten...,[2],0,2
18617,ttrpg.network,rpg,4,4866983,"No, I don’t. Iraq was a mistake, and the only ...",This community is for meaningful discussions o...,2024-02-01T19:25:23.264485Z,2024-02-02T00:21:23.015883Z,Flamewar,0,{'rules': {1: 'Do not distribute pirate conten...,[2],0,2

In [17]:
df.extracted_rules_json = df.extracted_rules_json.apply(literal_eval)

In [18]:
df.content.describe()

count                                                 17254
unique                                                16890
top        ![transshork-happy](https://www.hexbear.net/p...
freq                                                     30
Name: content, dtype: object

In [19]:
df[df.content.apply(lambda x: "permanently deleted" in x.lower())]

Empty DataFrame
Columns: [Unnamed: 0, instance, community_name, community_id, comment_id, content, community_description, comment_published, comment_removed, reason, language, exrtacted_rules, extracted_rules_json, rule_numbers, mapped_reasons, is_mass_removed, Unnamed: 0.1, rule]
Index: []

In [20]:
for _, row in df.iterrows():
    break

In [21]:
data = list(map(lambda row: dict(rules=row['extracted_rules_json']['rules'],
                community_id=row['community_id'],
                comment_id=row['comment_id'],
                comment=row['content'],
                instance=row['instance'],
                rule_number = int(row['rule']),
                reason=row['reason'],
                removed=True,
                ), df.to_dict(orient='records')))

In [22]:
data[0]

{'rules': {1: 'All posts must be related to the AniSocial website.',
  2: 'Be kind and respectful to one another.',
  3: 'Do not impersonate another person or entity.',
  4: 'Do not create announcement posts if you are not an admin.'},
 'community_id': 34,
 'comment_id': 2243845,
 'comment': '🤡',
 'instance': 'ani.social',
 'rule_number': 2,
 'reason': 'Breaks community rule: "2. Be kind and respectful to one another."',
 'removed': True}

In [23]:
max_qs= max(map(lambda x: len(x['rules']), data))

In [24]:
max_qs

99

In [25]:
list(filter(lambda x: len(x['rules'])==99, data))

[{'rules': {1: 'All Lemmy.ca rules apply here.',
   2: 'Everyone (see rules 4 and 98) is welcome.',
   3: 'If youve seen a question 100 times answer it the 101st time or ignore it.  Even better, write a complete, detailed answer and suggest that the mod(s) pin it to the community.',
   4: 'There will be ZERO tolerance for shaming, brigading, harassment, or other nonsense of those who keep and process chickens.  You will be permanently banned the first time.',
   5: 'No, its not a calcium deficiency.  Wrinkled eggs are the result of insufficient or insufficiently viscous albumen.  Tiny eggs and missing shells are misfires.  They happen.',
   6: 'If you post a picture that includes a dead animal or blood mark it NSFW.  Were not going to tolerate the militant anti-hunting and anti-farming bullshit here but were also not going to tolerate people rubbing their hunting and harvesting in peoples faces.',
   7: '',
   8: '',
   9: '',
   10: '',
   11: '',
   12: '',
   13: '',
   14: '',
   15: '',
   16: '',
   17: '',
   18: '',
   19: '',
   20: '',
   21: '',
   22: '',
   23: '',
   24: '',
   25: '',
   26: '',
   27: '',
   28: '',
   29: '',
   30: '',
   31: '',
   32: '',
   33: '',
   34: '',
   35: '',
   36: '',
   37: '',
   38: '',
   39: '',
   40: '',
   41: '',
   42: '',
   43: '',
   44: '',
   45: '',
   46: '',
   47: '',
   48: '',
   49: '',
   50: '',
   51: '',
   52: '',
   53: '',
   54: '',
   55: '',
   56: '',
   57: '',
   58: '',
   59: '',
   60: '',
   61: '',
   62: '',
   63: '',
   64: '',
   65: '',
   66: '',
   67: '',
   68: '',
   69: '',
   70: '',
   71: '',
   72: '',
   73: '',
   74: '',
   75: '',
   76: '',
   77: '',
   78: '',
   79: '',
   80: '',
   81: '',
   82: '',
   83: '',
   84: '',
   85: '',
   86: '',
   87: '',
   88: '',
   89: '',
   90: '',
   91: '',
   92: '',
   93: '',
   94: '',
   95: '',
   96: '',
   97: 'If you present something as fact and are asked to provide proof or a source provide proof or a source. Proof must be from a reliable source.',
   98: 'Dont be a dick.',
   99: 'The mod(s) have the final say.'},
  'community_id': 56378,
  'comment_id': 3108870,
  'comment': 'https://investigations.peta.org/wp-content/uploads/2021/02/happy-egg-co-hens-on-free-range-egg-farm.jpg\n\nThis is free range.\n\nhttps://investigations.peta.org/wp-content/uploads/2021/02/hen-on-a-free-range-egg-farm.jpg\n\nThey are suffering.',
  'instance': 'lemmy.ca',
  'rule_number': 4,
  'reason': 'Rule 4',
  'removed': True}]

In [26]:
from hashlib import md5


def format_rule(rule_n, rule_text, custom_rule_tokens=False): 
    to_return = rule_text
    if rule_n is not None:
        if custom_rule_tokens:
            to_return = f"[RULE{rule_n}] "+to_return
        else:
            to_return = f"{rule_n}. "+to_return
    return to_return
def data_to_qa(entry, custom_tokens = True, custom_rule_tokens=False):
    answer_start_char = 0
    answer_end_char = 0
    rules = ""
    for rule_n, rule_text in entry['rules'].items():
        formatted_rule_text = format_rule(rule_n, rule_text, custom_rule_tokens=custom_rule_tokens)
        if rule_n ==entry['rule_number']:
            answer_start_char = len(rules)
            answer_end_char = answer_start_char + len(formatted_rule_text)
        rules += formatted_rule_text+'\n'
    rules = rules[:-1] # remove final newline
    if custom_tokens:
        rules = f"""
[BOR]
{rules}
[EOR]
"""
        answer_start_char+=len(f"""
[BOR]
""")
        answer_end_char+=len(f"""
[BOR]
""")
        
    question = "Check if in the following message there is unsafe content according to the specified policy and categories:" 
    context = rules
    if custom_tokens: 
        context+=f"""
[BOC]
{entry['comment']}
[EOC]
"""
    else:
        context+=entry['comment']
    answers = dict(rule_number= entry['rule_number'],
                   text= entry['rules'][entry['rule_number']],
                   removed= entry['removed'],
                   start_char= answer_start_char,
                   end_char= answer_end_char,
                   )   
    
    entry=entry.copy()
    entry['rules']={str(i):j for i, j in entry['rules'].items()}
    return dict(question=question, context=context, answers=answers, entry=entry, id=md5((question+context).encode('utf-8')).hexdigest())

In [27]:
qa = list(map(data_to_qa, data))

In [28]:
from transformers import (
    BertTokenizer,
    BertForQuestionAnswering,
    BertTokenizerFast
)

tokenizer = BertTokenizerFast.from_pretrained("bert-base-uncased")

print(tokenizer.all_special_tokens)

['[UNK]', '[SEP]', '[PAD]', '[CLS]', '[MASK]']

In [29]:
tokenizer.add_special_tokens(
    {"additional_special_tokens": ["[BOR]", "[EOR]", "[BOC]", "[EOC]"]}
)
print(tokenizer.all_special_tokens)

['[UNK]', '[SEP]', '[PAD]', '[CLS]', '[MASK]', '[BOR]', '[EOR]', '[BOC]', '[EOC]']

In [30]:
model = BertForQuestionAnswering.from_pretrained("bert-base-uncased")
model.resize_token_embeddings(len(tokenizer))

Some weights of BertForQuestionAnswering were not initialized from the model checkpoint at bert-base-uncased and are newly initialized: ['qa_outputs.bias', 'qa_outputs.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
The new embeddings will be initialized from a multivariate normal distribution that has old embeddings' mean and covariance. As described in this article: https://nlp.stanford.edu/~johnhew/vocab-expansion.html. To disable this, use `mean_resizing=False`

Embedding(30526, 768, padding_idx=0)

In [31]:
import torch

context = "[BOR] The quick brown fox jumps over the lazy dog. [EOR]"
question = "[BOC] What color is the fox?[EOC]"

inputs = tokenizer(question, context, return_tensors="pt")

start_positions = torch.tensor([1])
end_positions = torch.tensor([4])

outputs = model(**inputs, start_positions=start_positions, end_positions=end_positions)

In [32]:
inputs.tokens()[outputs.start_logits.argmax().item():outputs.end_logits.argmax().item()]

['what', 'color', 'is']

In [33]:
import datasets

In [34]:
qa[0]

{'question': 'Check if in the following message there is unsafe content according to the specified policy and categories:',
 'context': '\n[BOR]\n1. All posts must be related to the AniSocial website.\n2. Be kind and respectful to one another.\n3. Do not impersonate another person or entity.\n4. Do not create announcement posts if you are not an admin.\n[EOR]\n\n[BOC]\n🤡\n[EOC]\n',
 'answers': {'rule_number': 2,
  'text': 'Be kind and respectful to one another.',
  'removed': True,
  'start_char': 62,
  'end_char': 103},
 'entry': {'rules': {'1': 'All posts must be related to the AniSocial website.',
   '2': 'Be kind and respectful to one another.',
   '3': 'Do not impersonate another person or entity.',
   '4': 'Do not create announcement posts if you are not an admin.'},
  'community_id': 34,
  'comment_id': 2243845,
  'comment': '🤡',
  'instance': 'ani.social',
  'rule_number': 2,
  'reason': 'Breaks community rule: "2. Be kind and respectful to one another."',
  'removed': True},
 'id': '320f1623241c387e6ed59050bccf4949'}

In [35]:
examples=datasets.Dataset.from_list(qa)

In [36]:
examples

Dataset({
    features: ['question', 'context', 'answers', 'entry', 'id'],
    num_rows: 17254
})

In [37]:
inputs = tokenizer(
    examples["question"],
    examples["context"],
    max_length=384,
    truncation="only_second",
    return_offsets_mapping=True,
    padding="max_length",
)

offset_mapping = inputs.pop("offset_mapping")
answers = examples["answers"]
start_positions = []
end_positions = []


for i, offset in enumerate(offset_mapping):
    answer = answers[i]
    sequence_ids = inputs.sequence_ids(i)
    # sequence_ids.reverse()

    # Find the start and end of the context
    idx = 0
    while sequence_ids[idx] != 1:
        idx += 1
    context_start = idx
    while sequence_ids[idx] == 1:
        idx += 1
    context_end = idx - 1

    # If the answer is not fully inside the context, label it (0, 0)
    start_char = answer["start_char"]
    end_char = answer["end_char"]
    if offset[context_start][0] > end_char or offset[context_end][1] < start_char:
        start_positions.append(0)
        end_positions.append(0)
    else:
        # Otherwise it's the start and end token positions
        idx = context_start
        while idx <= context_end and offset[idx][0] <= start_char:
            idx += 1
        start_positions.append(idx - 1)

        idx = context_end
        while idx >= context_start and offset[idx][1] > end_char:
            idx -= 1
        end_positions.append(idx + 1)

inputs["start_positions"] = start_positions
inputs["end_positions"] = end_positions

In [38]:
example_idx = 30

qa[example_idx]['context'][qa[example_idx]['answers']['start_char']:qa[example_idx]['answers']['end_char']]

'9. Keine Polemik, keine Köderbeiträge, keine Falschmeldungen'

In [39]:
inputs[example_idx].tokens[start_positions[example_idx]:end_positions[example_idx]]

['9',
 '.',
 'kei',
 '##ne',
 'pole',
 '##mi',
 '##k',
 ',',
 'kei',
 '##ne',
 'ko',
 '##der',
 '##bei',
 '##tra',
 '##ge',
 ',',
 'kei',
 '##ne',
 'fa',
 '##ls',
 '##ch',
 '##mel',
 '##dun',
 '##gen']

In [40]:
examples[0]

{'question': 'Check if in the following message there is unsafe content according to the specified policy and categories:',
 'context': '\n[BOR]\n1. All posts must be related to the AniSocial website.\n2. Be kind and respectful to one another.\n3. Do not impersonate another person or entity.\n4. Do not create announcement posts if you are not an admin.\n[EOR]\n\n[BOC]\n🤡\n[EOC]\n',
 'answers': {'end_char': 103,
  'removed': True,
  'rule_number': 2,
  'start_char': 62,
  'text': 'Be kind and respectful to one another.'},
 'entry': {'comment': '🤡',
  'comment_id': 2243845,
  'community_id': 34,
  'instance': 'ani.social',
  'reason': 'Breaks community rule: "2. Be kind and respectful to one another."',
  'removed': True,
  'rule_number': 2,
  'rules': {'0': None,
   '1': 'All posts must be related to the AniSocial website.',
   '10': None,
   '11': None,
   '12': None,
   '13': None,
   '14': None,
   '15': None,
   '16': None,
   '17': None,
   '18': None,
   '19': None,
   '2': 'Be kind and respectful to one another.',
   '20': None,
   '21': None,
   '22': None,
   '23': None,
   '24': None,
   '25': None,
   '26': None,
   '27': None,
   '28': None,
   '29': None,
   '3': 'Do not impersonate another person or entity.',
   '30': None,
   '31': None,
   '32': None,
   '33': None,
   '34': None,
   '35': None,
   '36': None,
   '37': None,
   '38': None,
   '39': None,
   '4': 'Do not create announcement posts if you are not an admin.',
   '40': None,
   '41': None,
   '42': None,
   '43': None,
   '44': None,
   '45': None,
   '46': None,
   '47': None,
   '48': None,
   '49': None,
   '5': None,
   '50': None,
   '51': None,
   '52': None,
   '53': None,
   '54': None,
   '55': None,
   '56': None,
   '57': None,
   '58': None,
   '59': None,
   '6': None,
   '60': None,
   '61': None,
   '62': None,
   '63': None,
   '64': None,
   '65': None,
   '66': None,
   '67': None,
   '68': None,
   '69': None,
   '7': None,
   '70': None,
   '71': None,
   '72': None,
   '73': None,
   '74': None,
   '75': None,
   '76': None,
   '77': None,
   '78': None,
   '79': None,
   '8': None,
   '80': None,
   '81': None,
   '82': None,
   '83': None,
   '84': None,
   '85': None,
   '86': None,
   '87': None,
   '88': None,
   '89': None,
   '9': None,
   '90': None,
   '91': None,
   '92': None,
   '93': None,
   '94': None,
   '95': None,
   '96': None,
   '97': None,
   '98': None,
   '99': None}},
 'id': '320f1623241c387e6ed59050bccf4949'}

In [41]:
pd.read_csv('../data/processed/positive_data_community_descriptions.csv', nrows=1, index_col=0)

,community_name,community_description,comment_id,description,extracted_rules
0,10_0,I live in a prison called My Parents Basement ...,"[13586358, 5430356, 1324064, 501042, 467224, 4...",I live in a prison called My Parents Basement ...,"\n{""Rules"": [{""Number"": ""1"", ""Description"": ""D..."

In [42]:
df.columns

Index(['Unnamed: 0', 'instance', 'community_name', 'community_id',
       'comment_id', 'content', 'community_description', 'comment_published',
       'comment_removed', 'reason', 'language', 'exrtacted_rules',
       'extracted_rules_json', 'rule_numbers', 'mapped_reasons',
       'is_mass_removed', 'Unnamed: 0.1', 'rule'],
      dtype='object')

In [43]:
pd.read_csv('../data/processed/positive_data_with_extracted_rules.csv', nrows=1, index_col=0)

,community_name,community_id,comment_id,content,community_description,language,exrtacted_rules
0,saas,557426,13322168,I would look into queues and a background task...,Software As a Service Companies — The Future O...,37,"\n{""Rules"": []}\n"

In [44]:
comment_data_root = r"D:\PycharmProjects\lemmymod\data\raw\comments"

In [45]:
df[['instance', 'community_id', 'community_name']].drop_duplicates()

               instance  community_id     community_name
0            ani.social            34               meta
4            ani.social         36835           thiccmoe
5            ani.social         57558          meganemoe
7            ani.social          8073            fangmoe
8           aussie.zone            58          melbourne
...                 ...           ...                ...
18559        slrpnk.net         30848        shoplifting
18561        slrpnk.net            16              memes
18571  startrek.website             5  daystrominstitute
18575  startrek.website             2           startrek
18611     thelemmy.club        480575               news

[385 rows x 3 columns]

In [46]:
df[['instance', 'community_id', 'community_name']].drop_duplicates().groupby('community_name').size().sort_values(ascending=False).head(20)

community_name
memes                   7
news                    5
politics                5
games                   4
vegan                   4
worldnews               4
gaming                  3
mentalhealth            3
technology              3
traaaaaaannnnnnnnnns    2
funny                   2
transgender             2
canada                  2
india                   2
fediverse               2
antiwork                2
formula1                2
meta                    2
movies                  2
conservative            2
dtype: int64

In [47]:

df[['instance', 'community_id', 'community_name']].drop_duplicates().groupby('community_id').size().sort_values(ascending=False).head(20)

community_id
2         13
16         5
3          4
5          3
58         3
8          3
13         3
18         3
29         3
32         3
10         2
49         2
4          2
6          2
9          2
50         2
12         2
28         2
495508     1
497726     1
dtype: int64

In [69]:
from tqdm import tqdm
from itertools import islice

community_descriptions = defaultdict(set)
for instance in tqdm(os.listdir(comment_data_root)):
    for community in os.listdir(os.path.join(comment_data_root, instance)):
        with open(os.path.join(comment_data_root, instance,community), encoding='utf8') as f:
            for l in islice(map(json.loads, f), 100):
                community_descriptions[(instance, community, l['community']['id'], l['community']['actor_id'])].add(json.dumps(l['community'], sort_keys=True))

100%|██████████| 419/419 [04:50<00:00,  1.44it/s]

In [72]:
from collections import Counter
Counter(map(len, community_descriptions.values()))

Counter({1: 12212, 2: 56, 3: 2, 5: 1, 4: 1})

In [109]:
commies = pd.DataFrame(json.loads(f)|dict(file=b, instance=a) for (a, b, c, d), e in community_descriptions.items() for f in e)

In [110]:
commies

,actor_id,banner,deleted,description,hidden,icon,id,instance_id,local,name,nsfw,posting_restricted_to_mods,published,removed,title,updated,visibility,file,instance
0,https://0xdd.org.ru/c/joplinrus,https://0xdd.org.ru/pictrs/image/bcb10306-b178...,False,[![](https://img.shields.io/lemmy/joplinrus%40...,False,https://0xdd.org.ru/pictrs/image/84218024-78d4...,93,11.0,True,joplinrus,False,False,2024-04-11T08:08:56.697271Z,False,Joplin на русском,2024-04-24T18:34:38.164465Z,Public,joplinrus_comments.jsonl,0xdd.org.ru
1,https://0xdd.org.ru/c/kazan,https://0xdd.org.ru/pictrs/image/bc6c1945-1d5a...,False,NaN,False,NaN,4,11.0,True,kazan,False,False,2022-04-15T06:14:22.238743Z,False,Kazan city related,2023-03-26T19:32:16.766057Z,Public,kazan_comments.jsonl,0xdd.org.ru
2,https://0xdd.org.ru/c/main,NaN,False,root,False,https://0xdd.org.ru/pictrs/image/cf61a8d4-873b...,2,11.0,True,main,False,False,2022-04-13T12:35:22.236344Z,False,root,2024-04-12T07:09:07.581781Z,Public,main_comments.jsonl,0xdd.org.ru
3,https://1337lemmy.com/c/chibears,https://1337lemmy.com/pictrs/image/d5bbc04b-70...,False,Welcome to the Lemmy home of the Chicago Bears,False,https://1337lemmy.com/pictrs/image/c32c86c0-3b...,78,1.0,True,chibears,False,False,2023-06-05T19:47:10.954280Z,False,Chicago Bears,2024-08-08T20:12:59.499833Z,Public,chibears_comments.jsonl,1337lemmy.com
4,https://1337lemmy.com/c/chicubs,https://1337lemmy.com/pictrs/image/b4da266f-ff...,False,A Lemmy community for the Chicago Cubs,False,https://1337lemmy.com/pictrs/image/8063017c-d4...,129,1.0,True,chicubs,False,False,2023-06-06T00:07:55.848219Z,False,Chicago Cubs,2024-08-08T20:20:19.086489Z,Public,chicubs_comments.jsonl,1337lemmy.com
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12334,https://zerobytes.monster/c/usenet,NaN,False,We are a thriving community dedicated to helpi...,False,https://b.thumbs.redditmedia.com/xQ72fPNEEClpF...,20,1.0,True,usenet,False,True,2024-03-24T15:21:33.733396Z,False,r/usenet - Usenet Discussion,NaN,NaN,usenet_comments.jsonl,zerobytes.monster
12335,https://zerobytes.monster/c/utterlyuniquephotos,NaN,False,Old and new photographs that can sometimes be ...,False,NaN,5705,1.0,True,utterlyuniquephotos,False,True,2024-04-21T07:44:42.539803Z,False,UtterlyUniquePhotos,NaN,NaN,utterlyuniquephotos_comments.jsonl,zerobytes.monster
12336,https://zerobytes.monster/c/videos,NaN,False,Reddit's main subreddit for videos. Please rea...,False,https://a.thumbs.redditmedia.com/mtwnduVr0DnrK...,1783,1.0,True,videos,False,True,2024-04-01T08:33:01.664288Z,False,/r/videos,NaN,NaN,videos_comments.jsonl,zerobytes.monster
12337,https://zerobytes.monster/c/weird,NaN,False,"The subreddit for the weird, strange, odd and ...",False,https://a.thumbs.redditmedia.com/1cuMopH1rv_to...,1121,1.0,True,weird,False,True,2024-03-29T07:35:48.061076Z,False,Weird,NaN,NaN,weird_comments.jsonl,zerobytes.monster
12338,https://zoo.splitlinux.org/c/splitlinux,https://zoo.splitlinux.org/pictrs/image/2ff5d8...,False,The Linux distribution that splits your variou...,False,https://zoo.splitlinux.org/pictrs/image/5609b4...,3,50.0,True,splitlinux,False,False,2022-12-11T07:55:44.344568,False,Split Linux,2024-03-11T22:59:14.071488,NaN,splitlinux_comments.jsonl,zoo.splitlinux.org

In [111]:
commies.groupby('actor_id').size().sort_values(ascending=False).head(20)

actor_id
https://lemm.ee/c/stopkillinggames                 5
https://lemmy.ca/c/linuxphones                     4
https://ani.social/c/dandadumber                   3
https://lemmy.zip/c/pathofexile2                   3
https://hexbear.net/c/askchapo                     2
https://lemmy.one/c/theprivacypodcast              2
https://hexbear.net/c/bloomer                      2
https://hexbear.net/c/canada                       2
https://hexbear.net/c/chapotraphouse               2
https://hexbear.net/c/chapotraphouse3              2
https://lemmy.sdf.org/c/linux_video_editing        2
https://hexbear.net/c/comics                       2
https://lemmy.world/c/ai_characters_and_content    2
https://feddit.org/c/tierwelt                      2
https://hexbear.net/c/counterpropaganda            2
https://hexbear.net/c/covid                        2
https://hexbear.net/c/creepy                       2
https://hexbear.net/c/disabled                     2
https://hexbear.net/c/doomer                       2
https://hexbear.net/c/dredge_tank                  2
dtype: int64

In [112]:
commies.drop_duplicates(inplace=True)

In [113]:
commies.describe(include='all')

,actor_id,banner,deleted,description,hidden,icon,id,instance_id,local,name,nsfw,posting_restricted_to_mods,published,removed,title,updated,visibility,file,instance
count,12339,4770,12339,10585,12339,8211,1.233900e+04,12321.000000,12339,12339,12339,12339,12339,12339,12339,7756,6810,12339,12339
unique,12204,4693,2,10376,1,8103,NaN,NaN,1,9739,2,2,12200,2,10836,7680,1,9739,313
top,https://lemm.ee/c/stopkillinggames,https://lemmy.ca/pictrs/image/e73af48c-3a90-4f...,False,,False,https://b.thumbs.redditmedia.com/JQgfgZVmHIlgd...,NaN,NaN,True,meta,False,False,2024-10-29T08:06:30.295193Z,False,test,2024-11-13T02:20:12.755427Z,Public,meta_comments.jsonl,lemmy.world
freq,5,4,12327,44,12339,5,NaN,NaN,12339,40,11331,11456,5,12338,17,2,6810,40,3711
mean,NaN,NaN,NaN,NaN,NaN,NaN,8.874522e+04,97.820631,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
std,NaN,NaN,NaN,NaN,NaN,NaN,1.864985e+05,166.554916,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
min,NaN,NaN,NaN,NaN,NaN,NaN,2.000000e+00,1.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25%,NaN,NaN,NaN,NaN,NaN,NaN,2.619000e+03,1.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
50%,NaN,NaN,NaN,NaN,NaN,NaN,1.773500e+04,1.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
75%,NaN,NaN,NaN,NaN,NaN,NaN,6.725750e+04,119.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
max,NaN,NaN,NaN,NaN,NaN,NaN,2.429513e+06,779.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [130]:
multiple_description_communities = set(map(lambda x: x[0], filter(lambda x: x[1]>1, commies.groupby('actor_id').description.nunique().to_dict().items())))

In [131]:
len(multiple_description_communities)

27

In [134]:
# remove communities with multiple descriptions
commies = commies[~commies.actor_id.isin(multiple_description_communities)]

In [135]:
from transformers import pipeline

text = [
    "Brevity is the soul of wit.",
    "Amor, ch'a nullo amato amar perdona."
]

model_ckpt = "papluca/xlm-roberta-base-language-detection"
pipe = pipeline("text-classification", model=model_ckpt)
pipe(text, top_k=1, truncation=True)

config.json:   0%|          | 0.00/1.42k [00:00<?, ?B/s]

F:\PycharmProjects\ruler\.venv\lib\site-packages\huggingface_hub\file_download.py:140: UserWarning: `huggingface_hub` cache-system uses symlinks by default to efficiently store duplicated files but your machine does not support them in C:\Users\hide\.cache\huggingface\hub\models--papluca--xlm-roberta-base-language-detection. Caching files will still work but in a degraded version that might require more space on your disk. This warning can be disabled by setting the `HF_HUB_DISABLE_SYMLINKS_WARNING` environment variable. For more details, see https://huggingface.co/docs/huggingface_hub/how-to-cache#limitations.
To support symlinks on Windows, you either need to activate Developer Mode or to run Python as an administrator. In order to activate developer mode, see this article: https://docs.microsoft.com/en-us/windows/apps/get-started/enable-your-device-for-development
  warnings.warn(message)

model.safetensors:   0%|          | 0.00/1.11G [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/502 [00:00<?, ?B/s]

sentencepiece.bpe.model:   0%|          | 0.00/5.07M [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/9.08M [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/239 [00:00<?, ?B/s]

Device set to use cuda:0

[[{'label': 'en', 'score': 0.8889274001121521}],
 [{'label': 'it', 'score': 0.9120121002197266}]]

In [144]:
commies['lang'] = pipe(commies.description.fillna("").values.tolist(), top_k=1, truncation=True)

In [146]:
commies['lang_label'] = commies.lang.apply(lambda x:x[0]['label'])
commies['lang_score'] = commies.lang.apply(lambda x:x[0]['score'])

In [149]:
# remove non-eng
commies[commies.lang_label != 'en'][['lang_label', 'lang_score', 'description', 'actor_id'] ]

,lang_label,lang_score,description,actor_id
0,ru,0.994144,[![](https://img.shields.io/lemmy/joplinrus%40...,https://0xdd.org.ru/c/joplinrus
1,th,0.074096,NaN,https://0xdd.org.ru/c/kazan
8,th,0.074096,NaN,https://7c4tx1.lem.rocks/c/fake2
9,th,0.074096,NaN,https://7c4tx1.lem.rocks/c/test
10,th,0.074096,NaN,https://academy.garden/c/askastronomy
...,...,...,...,...
12253,th,0.074096,NaN,https://yall.theatl.social/c/atlutd
12259,th,0.074096,NaN,https://yall.theatl.social/c/politics
12262,th,0.074096,NaN,https://yall.theatl.social/c/technology
12314,sw,0.305939,jugkfmghgug.,https://zerobytes.monster/c/mildlyinfuriating
12326,th,0.074096,NaN,https://zerobytes.monster/c/requests

In [151]:
commies = commies[commies.lang_label == 'en']

In [152]:
len(commies)

9268

In [153]:
comm_rules = pd.read_csv('../data/processed/positive_data_community_descriptions.csv', index_col=0)

In [154]:
comm_rules.head()

,community_name,community_description,comment_id,description,extracted_rules
0,10_0,I live in a prison called My Parents Basement ...,"[13586358, 5430356, 1324064, 501042, 467224, 4...",I live in a prison called My Parents Basement ...,"\n{""Rules"": [{""Number"": ""1"", ""Description"": ""D..."
1,12in12,A place to post the list of games you hope to ...,"[14769620, 14672881, 14541371, 14541361, 13634...",A place to post the list of games you hope to ...,"\n{""Rules"": [{""Number"": ""1"", ""Description"": ""D..."
2,12ozmouse,![rectangular business man](https://adultswim....,"[442244, 271729]",![rectangular business man](https://adultswim....,"\n{""Rules"": []}\n"
3,14ers,"For discussion on hiking up to 14,000 feet and...",[1032510],"For discussion on hiking up to 14,000 feet and...","\n{""Rules"": [{""Number"": ""14,000 feet"", ""Descri..."
4,15minutecity,Discussion about the path towards 15 minute ci...,"[11360026, 11069887, 9997165, 9994133, 9931021...",Discussion about the path towards 15 minute ci...,"\n{""Rules"": [{""Number"": ""15"", ""Description"": ""..."

In [167]:
w_rules = pd.merge(commies, comm_rules[['description', 'extracted_rules']], on='description', how='inner')

In [168]:
w_rules

,actor_id,banner,deleted,description,hidden,icon,id,instance_id,local,name,...,removed,title,updated,visibility,file,instance,lang,lang_label,lang_score,extracted_rules
0,https://1337lemmy.com/c/chibears,https://1337lemmy.com/pictrs/image/d5bbc04b-70...,False,Welcome to the Lemmy home of the Chicago Bears,False,https://1337lemmy.com/pictrs/image/c32c86c0-3b...,78,1.0,True,chibears,...,False,Chicago Bears,2024-08-08T20:12:59.499833Z,Public,chibears_comments.jsonl,1337lemmy.com,"[{'label': 'en', 'score': 0.8470140099525452}]",en,0.847014,"\n{""Rules"": []}\n"
1,https://1337lemmy.com/c/chicubs,https://1337lemmy.com/pictrs/image/b4da266f-ff...,False,A Lemmy community for the Chicago Cubs,False,https://1337lemmy.com/pictrs/image/8063017c-d4...,129,1.0,True,chicubs,...,False,Chicago Cubs,2024-08-08T20:20:19.086489Z,Public,chicubs_comments.jsonl,1337lemmy.com,"[{'label': 'en', 'score': 0.7887876629829407}]",en,0.788788,"\n{""Rules"": []}\n"
2,https://1337lemmy.com/c/thesopranos,https://1337lemmy.com/pictrs/image/4aa073a9-12...,False,Lemmy community dedicated to the HBO hit TV se...,False,https://1337lemmy.com/pictrs/image/421a5517-47...,125,1.0,True,thesopranos,...,False,The Sopranos,2024-08-08T20:18:56.942406Z,Public,thesopranos_comments.jsonl,1337lemmy.com,"[{'label': 'en', 'score': 0.8831620812416077}]",en,0.883162,"\n{""Rules"": []}\n"
3,https://academy.garden/c/astrophysics,NaN,False,A community for Astrophysics and any branches ...,False,NaN,4,1.0,True,astrophysics,...,False,Astrophysics,NaN,NaN,astrophysics_comments.jsonl,academy.garden,"[{'label': 'en', 'score': 0.9100855588912964}]",en,0.910086,"\n{""Rules"": []}\n"
4,https://academy.garden/c/cosmology,NaN,False,"A place for questions, discussions, and articl...",False,NaN,6,1.0,True,cosmology,...,False,Cosmology,NaN,NaN,cosmology_comments.jsonl,academy.garden,"[{'label': 'en', 'score': 0.9532097578048706}]",en,0.953210,"\n{""Rules"": [{""Number"": ""1"", ""Description"": ""A..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4698,https://zerobytes.monster/c/selfhosted,NaN,False,"A place to share, discuss, discover, assist wi...",False,NaN,1108,1.0,True,selfhosted,...,False,Self-Hosted Alternatives to Popular Services,NaN,NaN,selfhosted_comments.jsonl,zerobytes.monster,"[{'label': 'en', 'score': 0.8175429701805115}]",en,0.817543,"\n{""Rules"": [{""Number"": ""1"", ""Description"": ""A..."
4699,https://zerobytes.monster/c/tech,NaN,False,The goal of /r/tech is to provide a space dedi...,False,https://f.thumbs.redditmedia.com/kI7eGVG6kaObG...,1804,1.0,True,tech,...,False,/r/tech: Technological innovations and changes,NaN,NaN,tech_comments.jsonl,zerobytes.monster,"[{'label': 'en', 'score': 0.8177855610847473}]",en,0.817786,"\n{""Rules"": []}\n"
4700,https://zerobytes.monster/c/torrents,NaN,False,🌊 Dedicated to in-depth discussion of digital ...,False,NaN,1100,1.0,True,torrents,...,False,Torrents: ᴘ2ᴘ ꜰɪʟᴇ ꜱʜᴀʀɪɴɢ,NaN,NaN,torrents_comments.jsonl,zerobytes.monster,"[{'label': 'en', 'score': 0.8934921026229858}]",en,0.893492,"\n{""Rules"": [{""Number"": """", ""Description"": """"}..."
4701,https://zerobytes.monster/c/utterlyuniquephotos,NaN,False,Old and new photographs that can sometimes be ...,False,NaN,5705,1.0,True,utterlyuniquephotos,...,False,UtterlyUniquePhotos,NaN,NaN,utterlyuniquephotos_comments.jsonl,zerobytes.monster,"[{'label': 'en', 'score': 0.9892084002494812}]",en,0.989208,"\n{""Rules"": [{""Number"": ""1"", ""Description"": ""O..."
4702,https://zerobytes.monster/c/weird,NaN,False,"The subreddit for the weird, strange, odd and ...",False,https://a.thumbs.redditmedia.com/1cuMopH1rv_to...,1121,1.0,True,weird,...,False,Weird,NaN,NaN,weird_comments.jsonl,zerobytes.monster,"[{'label': 'en', 'score': 0.9107978940010071}]",en,0.910798,"\n{""Rules"": []}\n"

In [199]:
def eval_rules(x):
    try:
        return len(literal_eval(x.strip().replace('\n\r\t', ""))['Rules'])
    except Exception as e:
        print(e)
        print(x)
        return -1
w_rules['n_rules'] = w_rules.extracted_rules.apply(eval_rules)

unterminated string literal (detected at line 1) (<unknown>, line 1)

{"Rules": [{"Number": "1", "Description": "Discussions must be around the Call of Duty:
WWII (2017) game."}]}

(unicode error) 'unicodeescape' codec can't decode bytes in position 38-42: truncated \uXXXX escape (<unknown>, line 1)

{"Rules": [{"Number": "1", "Description": "proper spelling is discouraged, have f\u00bmu!"}, {"Number": "2", "Description": "don\u2019t do anything that could compromise this community, so: \u2026 no porn \u2026 no hateful language \u2026 keep it relatively SFW. There\u2019s enough room on the internet for *volatile* nonsense elsehwhere."}]}

invalid character '‘' (U+2018) (<unknown>, line 1)

{"Rules": [{"Number": "1", "Description": "No bigotry: Including racism, sexism, homophobia, transphobia, or xenophobia."}, {"Number": "2", "Description": "Be respectful. Everyone should feel welcome here."}, {"Number": "3", "Description": "No NSFW content."}, {"Number": "4", "Description": "No Ads / Spamming."}, {"Number": "5", "Description": "Be thoughtful and helpful": even with ‘stupid’ questions. The world won’t be made better or worse by snarky comments schooling naive newcomers on Lemmy."}]}

invalid character '‘' (U+2018) (<unknown>, line 1)

{"Rules": [{"Number": "1", "Description": "No bigotry: Including racism, sexism, homophobia, transphobia, or xenophobia."}, {"Number": "2", "Description": "Be respectful. Everyone should feel welcome here."}, {"Number": "3", "Description": "No NSFW content."}, {"Number": "4", "Description": "No Ads / Spamming."}, {"Number": "5", "Description": "Be thoughtful and helpful": even with ‘stupid’ questions. The world won’t be made better or worse by snarky comments schooling naive newcomers on Lemmy."}]}

invalid character '‘' (U+2018) (<unknown>, line 1)

{"Rules": [{"Number": "1", "Description": "No bigotry: Including racism, sexism, homophobia, transphobia, or xenophobia."}, {"Number": "2", "Description": "Be respectful. Everyone should feel welcome here."}, {"Number": "3", "Description": "No NSFW content."}, {"Number": "4", "Description": "No Ads / Spamming."}, {"Number": "5", "Description": "Be thoughtful and helpful": even with ‘stupid’ questions. The world won\u2019t be made better or worse by snarky comments schooling naive newcomers on Lemmy."}]}

unterminated string literal (detected at line 1) (<unknown>, line 1)

{"Rules": [{"Number": "1", "Description": "Posts should start with a style tag when relevant:
[FRE] = Freestyle
[FOL] = Folkstyle
[GRE] = Greco-Roman
[JUD] = Judo
[MON] = Mongolian
[SUM] = Sumo"}, {"Number": "2", "Description": "No name-calling or other bad behavior."}, {"Number": "3", "Description": "Probably other stuff, but this seems good enough for now."}]}

invalid syntax (<unknown>, line 1)

{"Rules": [{"Number": "1", "Description": "No bigotry: Including racism, sexism, homophobia, transphobia, or xenophobia."}, {"Number": "2", "Description": "Be respectful. Everyone should feel welcome here."}, {"Number": "3", "Description": "No NSFW content."}, {"Number": "4", "Description": "No Ads / Spamming."}, {"Number": "5", "Description": "Be thoughtful and helpful": "even with ‘stupid’ questions. The world won’t be made better or worse by snarky comments schooling naive newcomers on Lemmy."}, {"Number": "6", "Description": "OC Only. All content should be original."}, {"Number": "7", "Description": "Photos/Videos/GIFs only. All posts should be photos, videos or gifs, no music playlists please."}]}

unterminated string literal (detected at line 1) (<unknown>, line 1)

{"Rules": [{"Number": "1", "Description": "Be nice to each other. Respect each others opinions and artistic choices."}, {"Number": "2", "Description": "Stay on topic, if you wish to discuss general linguistics, check out
!linguistics@mander.xyz ([Kbin link](/m/linguistics@mander.xyz))"}, {"Number": "3", "Description": "No low effort posts and comments. This also includes memes."}, {"Number": "4", "Description": "When referencing real life linguistics, make sure to cite your sources."}]}

In [201]:
w_rules[w_rules.n_rules < 0]

,actor_id,banner,deleted,description,hidden,icon,id,instance_id,local,name,...,title,updated,visibility,file,instance,lang,lang_label,lang_score,extracted_rules,n_rules
2237,https://lemmy.world/c/callofdutywwii,https://lemmy.world/pictrs/image/ecbede8d-8657...,False,Lemmy community for the Call of Duty: WWII gam...,False,https://lemmy.world/pictrs/image/6e13fb71-16ae...,221239,1.0,True,callofdutywwii,...,Call of Duty: WWII,2023-08-16T07:10:24.795183Z,NaN,callofdutywwii_comments.jsonl,lemmy.world,"[{'label': 'en', 'score': 0.7999177575111389}]",en,0.799918,"\n{""Rules"": [{""Number"": ""1"", ""Description"": ""D...",-1
2367,https://lemmy.world/c/discordianism,https://lemmy.world/pictrs/image/3aee9fcb-5a8e...,False,a place for discordian meems nd DIScu5hin\n\n-...,False,https://lemmy.world/pictrs/image/eab6cc90-d3c9...,40052,1.0,True,discordianism,...,D̶̫̉i̶̥̅ș̷̐c̴͍̕o̸̘͠r̴̘̊d̸̡̅i̷͚̒a̶̡͌n̶̻̄i̶̺̎s̷...,2023-08-04T19:38:40.249115Z,NaN,discordianism_comments.jsonl,lemmy.world,"[{'label': 'en', 'score': 0.9480313658714294}]",en,0.948031,"\n{""Rules"": [{""Number"": ""1"", ""Description"": ""p...",-1
2525,https://lemmy.world/c/fuckcorporations,NaN,False,A place to rant about corporations and franchi...,False,https://lemmy.world/pictrs/image/1d99a33c-bd41...,23828,1.0,True,fuckcorporations,...,Fuck Corporations,2023-06-21T04:13:06.999341Z,NaN,fuckcorporations_comments.jsonl,lemmy.world,"[{'label': 'en', 'score': 0.9823550581932068}]",en,0.982355,"\n{""Rules"": [{""Number"": ""1"", ""Description"": ""N...",-1
2534,https://lemmy.world/c/galaxys23ultra,NaN,False,Community for discussing the Samsung Galaxy S2...,False,https://lemmy.world/pictrs/image/f81bdfce-7454...,4170,1.0,True,galaxys23ultra,...,Samsung Galaxy S23 Ultra,2023-06-28T17:45:29.351950Z,NaN,galaxys23ultra_comments.jsonl,lemmy.world,"[{'label': 'en', 'score': 0.979334831237793}]",en,0.979335,"\n{""Rules"": [{""Number"": ""1"", ""Description"": ""N...",-1
2858,https://lemmy.world/c/monitors,NaN,False,A community for discussing computer monitors.\...,False,https://lemmy.world/pictrs/image/3d8b85c5-a05c...,4142,1.0,True,monitors,...,Monitors,2023-06-14T04:34:19.436974Z,NaN,monitors_comments.jsonl,lemmy.world,"[{'label': 'en', 'score': 0.9797235727310181}]",en,0.979724,"\n{""Rules"": [{""Number"": ""1"", ""Description"": ""N...",-1
3176,https://lemmy.world/c/sport_wrestling,https://lemmy.world/pictrs/image/963f515b-c680...,False,#A Community for All Types of Competitive Wres...,False,https://lemmy.world/pictrs/image/b3d1fbf4-29df...,25748,1.0,True,sport_wrestling,...,Sport Wrestling,2023-08-26T02:09:52.817907Z,NaN,sport_wrestling_comments.jsonl,lemmy.world,"[{'label': 'en', 'score': 0.9544361233711243}]",en,0.954436,"\n{""Rules"": [{""Number"": ""1"", ""Description"": ""P...",-1
3254,https://lemmy.world/c/thenightfeeling,https://lemmy.one/pictrs/image/9eb16ab3-8881-4...,False,The Night Feeling is the thoughtful nostalgic ...,False,https://lemmy.one/pictrs/image/76b9b27d-bbe0-4...,65420,1.0,True,thenightfeeling,...,The Night Feeling,2023-09-05T16:28:14.292402Z,NaN,thenightfeeling_comments.jsonl,lemmy.world,"[{'label': 'en', 'score': 0.9895755052566528}]",en,0.989576,"\n{""Rules"": [{""Number"": ""1"", ""Description"": ""N...",-1
3910,https://mander.xyz/c/conlangs,https://mander.xyz/pictrs/image/ba2c32b9-a3ea-...,False,Welcome to \n!conlangs@mander.xyz! This commun...,False,https://mander.xyz/pictrs/image/a625d30d-8a56-...,454190,385.0,True,conlangs,...,Constructed Languages,2024-06-30T19:50:27.140880Z,Public,conlangs_comments.jsonl,mander.xyz,"[{'label': 'en', 'score': 0.906060516834259}]",en,0.906061,"\n{""Rules"": [{""Number"": ""1"", ""Description"": ""B...",-1

In [203]:
l['comment']

{'ap_id': 'https://zoo.splitlinux.org/comment/4',
 'content': 'What are you looking for?\n\nI took this opportunity to write up a very rough guide: https://splitlinux.org/posts/installation--the-recommended-setup.html\n\n*Automation for creating containers is already on the roadmap.*',
 'creator_id': 2,
 'deleted': False,
 'distinguished': False,
 'id': 4,
 'language_id': 0,
 'local': True,
 'path': '0.4',
 'post_id': 406,
 'published': '2020-06-24T02:32:06.417895',
 'removed': False}

In [245]:
processed_ids=set()
modlog_root = r"D:\PycharmProjects\lemmymod\data\raw\modlogs"
for instance in tqdm(os.listdir(modlog_root)):
    removed_comments_modlog = os.path.join(modlog_root, instance, 'removed_comments.jsonl')
    if not os.path.isfile(removed_comments_modlog): continue
    with open(removed_comments_modlog, encoding='utf8') as f:
        # print(removed_comments_modlog)
        for l in reversed(list(map(json.loads, f))):
            processed_ids.add((l['comment']['ap_id'], l['mod_remove_comment']['id'], instance, l['community']['actor_id'], l['mod_remove_comment']['when_'], l['mod_remove_comment']['mod_person_id'],))

100%|██████████| 871/871 [06:56<00:00,  2.09it/s]

In [246]:
df_mods = pd.DataFrame(processed_ids, columns=['comment_ap_id', 'mod_remove_id', 'instance', 'community_actor_id', 'when_', 'mod_person_id']).drop_duplicates()

In [247]:
df_mods.groupby('comment_ap_id').size().sort_values(ascending=False).head(20)

comment_ap_id
https://links.hackliberty.org/comment/1936704    11614
https://lemmy.world/comment/8111150               5022
https://links.hackliberty.org/comment/1936711     4578
https://discuss.online/comment/8752950            3467
https://links.hackliberty.org/comment/1936710     2816
https://hexbear.net/comment/5207505               2426
https://links.hackliberty.org/comment/1936706     2112
https://discuss.online/comment/8716473            2108
https://links.hackliberty.org/comment/1936713     1937
https://discuss.online/comment/8718387            1894
https://lemmy.world/comment/6783471               1871
https://lemmynsfw.com/comment/559397              1862
https://lemmy.ml/comment/1674585                  1743
https://lemm.ee/comment/6698311                   1534
https://lemm.ee/comment/1582266                   1413
https://lemmy.one/comment/2109022                 1381
https://lemm.ee/comment/2801388                   1251
https://lemmy.dbzer0.com/comment/11016431         1193
https://lemmy.world/comment/1623948               1190
https://lemmy.world/comment/1483143               1142
dtype: int64

In [248]:
df_mods[df_mods.comment_ap_id=='https://lemmy.world/comment/1483143'].sort_values(['comment_ap_id','instance', 'community_actor_id','mod_remove_id',   'when_']).head(200)

,comment_ap_id,mod_remove_id,instance,community_actor_id,when_,mod_person_id
3079395,https://lemmy.world/comment/1483143,358,014450.xyz,https://lemmy.world/c/world,2023-07-20T04:13:46.565336Z,255144
2774390,https://lemmy.world/comment/1483143,359,014450.xyz,https://lemmy.world/c/world,2023-07-20T04:13:46.587037Z,255144
419116,https://lemmy.world/comment/1483143,360,014450.xyz,https://lemmy.world/c/world,2023-07-20T04:13:47.061876Z,255144
5457881,https://lemmy.world/comment/1483143,361,014450.xyz,https://lemmy.world/c/world,2023-07-20T04:13:47.097412Z,255144
6193498,https://lemmy.world/comment/1483143,362,014450.xyz,https://lemmy.world/c/world,2023-07-20T04:13:47.130929Z,255144
...,...,...,...,...,...,...
797120,https://lemmy.world/comment/1483143,935,feddit.nu,https://lemmy.world/c/world,2023-07-20T04:13:50.393319Z,441722
3561660,https://lemmy.world/comment/1483143,433,feddit.ro,https://lemmy.world/c/world,2023-07-20T04:13:46.535752Z,223264
6538234,https://lemmy.world/comment/1483143,434,feddit.ro,https://lemmy.world/c/world,2023-07-20T04:13:46.555696Z,223264
6040440,https://lemmy.world/comment/1483143,435,feddit.ro,https://lemmy.world/c/world,2023-07-20T04:13:46.897292Z,223264
2343646,https://lemmy.world/comment/1483143,436,feddit.ro,https://lemmy.world/c/world,2023-07-20T04:13:46.965104Z,223264

In [249]:
df_mods.groupby(['comment_ap_id', 
                 # 'mod_remove_id',
                 'instance',
                 'community_actor_id'
                 ]).size().sort_values(ascending=False)

comment_ap_id                        instance         community_actor_id
https://hexbear.net/comment/5207505  lemmy.one        https://hexbear.net/c/chapotraphouse    81
                                     lemmygrad.ml     https://hexbear.net/c/chapotraphouse    81
                                     lemmy.zip        https://hexbear.net/c/chapotraphouse    81
                                     hexbear.net      https://hexbear.net/c/chapotraphouse    81
                                     lemmy.today      https://hexbear.net/c/chapotraphouse    81
                                                                                              ..
https://beehaw.org/comment/3927459   lemmy.zip        https://lemmy.ml/c/comics                1
                                     lemmyland.com    https://lemmy.ml/c/comics                1
                                     lemy.lol         https://lemmy.ml/c/comics                1
                                     literature.cafe  https://lemmy.ml/c/comics                1
https://mander.xyz/comment/12064606  bitforged.space  https://lemmy.world/c/politicalmemes     1
Length: 6737249, dtype: int64

In [250]:
df_mods.groupby('comment_ap_id').community_actor_id.nunique().sort_values(ascending=False) # comment ap if and community actor id are 1:1; it's not the community of origin of the comment. is it the community originating the mod action?

comment_ap_id
https://zerobytes.monster/comment/9                          1
https://1337lemmy.com/comment/1085292                        1
https://1337lemmy.com/comment/1097551                        1
https://1337lemmy.com/comment/1252699                        1
https://1337lemmy.com/comment/1252797                        1
                                                            ..
https://alien.top/comment/212                                1
https://alien.top/comment/1970442                            1
https://alien.top/comment/1806877                            1
https://alien.top/comment/1806764                            1
https://abdl.link/users/luana/statuses/110537111341034205    1
Name: community_actor_id, Length: 278317, dtype: int64

In [251]:
df_mods[['comment_ap_id', 'community_actor_id']].drop_duplicates().head(200)

,comment_ap_id,community_actor_id
0,https://lemmy.world/comment/11914693,https://lemmy.world/c/world
1,https://sh.itjust.works/comment/15543519,https://lemmy.world/c/news
2,https://feddit.org/comment/3116907,https://feddit.org/c/europe
3,https://hexbear.net/comment/4263986,https://aussie.zone/c/australia
4,https://lemmy.dbzer0.com/comment/14651924,https://lemmy.world/c/world
...,...,...
195,https://infosec.pub/comment/8630354,https://mander.xyz/c/biodiversity
196,https://lemmy.dbzer0.com/comment/12046857,https://lemmy.ml/c/asklemmy
197,https://lemmy.world/comment/13662112,https://lemmy.world/c/news
198,https://lemmy.ca/comment/10090980,https://lemmy.ca/c/nostupidquestions
199,https://lemmy.world/comment/2101217,https://feddit.uk/c/clevercomebacks

In [256]:
df_mods.groupby(['comment_ap_id', 'mod_person_id', 'community_actor_id', 'when_']).size().sort_values(ascending=False).head()

comment_ap_id                       mod_person_id  community_actor_id                          when_
https://ds9.lemmy.ml/comment/16090  5185           https://ds9.lemmy.ml/c/for_testing_yet_ano  2024-08-06T14:20:24.945939Z    3
                                                                                               2024-08-06T14:20:30.035575Z    3
https://ds9.lemmy.ml/comment/16049  8906           https://voyager.lemmy.ml/c/test8            2024-05-20T09:24:12.761573Z    3
                                                                                               2024-05-20T09:24:12.830036Z    3
https://ds9.lemmy.ml/comment/16088  5185           https://ds9.lemmy.ml/c/for_testing_yet_ano  2024-08-06T13:34:19.899416Z    3
dtype: int64

In [253]:
df_mods[df_mods.comment_ap_id=='https://lemmy.world/comment/11419060']

,comment_ap_id,mod_remove_id,instance,community_actor_id,when_,mod_person_id
647,https://lemmy.world/comment/11419060,7447,distress.digital,https://lemmy.world/c/technology,2024-07-28T19:08:39.643491Z,80641
1168,https://lemmy.world/comment/11419060,1274,links.gayfr.online,https://lemmy.world/c/technology,2024-07-27T15:14:37.959101Z,5954
10185,https://lemmy.world/comment/11419060,7126,lemmy.digitalfall.net,https://lemmy.world/c/technology,2024-07-27T15:13:46.195313Z,636155
18383,https://lemmy.world/comment/11419060,27123,yiffit.net,https://lemmy.world/c/technology,2024-07-27T15:14:43.928373Z,1391787
47964,https://lemmy.world/comment/11419060,3119,lemmy.laitinlok.com,https://lemmy.world/c/technology,2024-07-27T15:14:38.786606,277
...,...,...,...,...,...,...
7182710,https://lemmy.world/comment/11419060,7223,nodesphere.site,https://lemmy.world/c/technology,2024-07-27T17:20:38.131687Z,392
7195273,https://lemmy.world/comment/11419060,8222,communick.news,https://lemmy.world/c/technology,2024-07-28T19:08:37.532900Z,171442
7216914,https://lemmy.world/comment/11419060,203,lm.eke.li,https://lemmy.world/c/technology,2024-07-27T15:14:59.737228,40
7223833,https://lemmy.world/comment/11419060,16023,lemmy.dexlit.xyz,https://lemmy.world/c/technology,2024-07-27T17:22:53.497131Z,371
7225527,https://lemmy.world/comment/11419060,31827,discuss.online,https://lemmy.world/c/technology,2024-07-27T17:20:47.554547Z,132320

In [227]:
l

{'mod_remove_comment': {'id': 6592,
  'mod_person_id': 233,
  'comment_id': 2002843,
  'reason': 'lemmy.ml rule 1',
  'removed': True,
  'when_': '2024-08-18T22:05:28.145572Z'},
 'comment': {'id': 2002843,
  'creator_id': 2777,
  'post_id': 2541452,
  'content': 'You should contact your primary care physician if the paranoia lasts longer then four hours or it can cause permanent damage. ',
  'removed': True,
  'published': '2024-08-18T21:57:09.958688Z',
  'deleted': False,
  'ap_id': 'https://lemmy.world/comment/11849720',
  'local': False,
  'path': '0.2002772.2002843',
  'distinguished': False,
  'language_id': 0},
 'commenter': {'id': 2777,
  'name': 'SatansMaggotyCumFart',
  'display_name': 'SatansMaggotyCumFart',
  'banned': False,
  'published': '2023-07-07T01:47:21.930728Z',
  'actor_id': 'https://lemmy.world/u/SatansMaggotyCumFart',
  'local': False,
  'deleted': False,
  'bot_account': False,
  'instance_id': 3},
 'post': {'id': 2541452,
  'name': 'Why do all of the posts on instances defederated from Lemmy.world remain untouched by the downvote bots that people just sicced on me? 🤔',
  'creator_id': 2097719,
  'community_id': 127,
  'removed': True,
  'locked': False,
  'published': '2024-08-18T21:49:45.492556Z',
  'deleted': False,
  'nsfw': False,
  'ap_id': 'https://lemmy.ml/post/19310571',
  'local': False,
  'language_id': 37,
  'featured_community': False,
  'featured_local': False},
 'community': {'id': 127,
  'name': 'asklemmy',
  'title': 'Asklemmy',
  'description': "A loosely moderated place to ask open-ended questions\n\n**[Search asklemmy](https://lemmy.ml/search?q=&type=Posts&listingType=All&communityId=8&page=1&sort=TopAll) 🔍**\n\nIf your post meets the following criteria, it's welcome here!\n\n1. Open-ended question\n2. Not offensive: at this point, we do not have the bandwidth to moderate overtly political discussions. Assume best intent and be excellent to each other.\n3. **Not regarding using or support for Lemmy**: [context](https://lemmy.ml/post/1223478), see the list of support communities and tools for finding communities below\n4. Not ad nauseam inducing: please make sure it is a question that would be new to most members\n5. [An actual topic of discussion](https://lemmy.ml/post/1239589)\n\nLooking for support? \n\n* [!lemmy_support@lemmy.ml](https://lemmy.ml/c/lemmy_support) \n* [!fediverse@lemmy.ml](https://lemmy.ml/c/fediverse) \n* [!selfhosted@lemmy.world](https://lemmy.world/c/selfhosted) \n\nLooking for a community? \n\n* [Lemmyverse](https://lemmyverse.net/communities): community search \n* [sub.rehab](https://sub.rehab/): maps old subreddits to fediverse options, marks official as such \n* [!lemmy411@lemmy.ca](https://lemmy.ca/c/lemmy411): a community for finding communities \n\n~Icon~ ~by~ ~@Double_A@discuss.tchncs.de~",
  'removed': False,
  'published': '2019-04-25T04:58:33.886275Z',
  'updated': '2023-07-27T08:58:41.602101Z',
  'deleted': False,
  'nsfw': False,
  'actor_id': 'https://lemmy.ml/c/asklemmy',
  'local': False,
  'icon': 'https://lemmy.ml/pictrs/image/d3d059e3-fa3d-45af-ac93-ac894beba378.png',
  'banner': 'https://lemmy.ml/pictrs/image/36d2d6b4-9133-43eb-a980-5aa44939b904.png',
  'hidden': False,
  'posting_restricted_to_mods': False,
  'instance_id': 8},
 'retrieved_utc': 1724019468.7541}

In [257]:
df.head()

,Unnamed: 0,instance,community_name,community_id,comment_id,content,community_description,comment_published,comment_removed,reason,language,exrtacted_rules,extracted_rules_json,rule_numbers,mapped_reasons,is_mass_removed,Unnamed: 0.1,rule
0,6,ani.social,meta,34,2243845,🤡,Welcome to the AniSocial Lemmy community!\n\nT...,2023-11-07T00:18:02.163076Z,2023-11-07T00:33:39.337517Z,"Breaks community rule: ""2. Be kind and respect...",37,"\n{""Rules"": [{""Number"": ""1"", ""Description"": ""A...",{'rules': {1: 'All posts must be related to th...,[2],['Be kind and respectful to one another.'],0,NaN,2
1,7,ani.social,meta,34,2243457,All three regarded instances have admins that ...,Welcome to the AniSocial Lemmy community!\n\nT...,2023-11-06T23:54:25.185884Z,2023-11-07T00:33:57.229908Z,"Breaks community rule: ""2. Be kind and respect...",37,"\n{""Rules"": [{""Number"": ""1"", ""Description"": ""A...",{'rules': {1: 'All posts must be related to th...,[2],['Be kind and respectful to one another.'],0,NaN,2
2,8,ani.social,meta,34,2243847,🤡,Welcome to the AniSocial Lemmy community!\n\nT...,2023-11-07T00:18:07.077425Z,2023-11-07T00:34:05.931024Z,"Breaks community rule: ""2. Be kind and respect...",37,"\n{""Rules"": [{""Number"": ""1"", ""Description"": ""A...",{'rules': {1: 'All posts must be related to th...,[2],['Be kind and respectful to one another.'],0,NaN,2
3,9,ani.social,meta,34,2243842,Can you please just leave me the fuck alone yo...,Welcome to the AniSocial Lemmy community!\n\nT...,2023-11-07T00:17:23.467802Z,2023-11-07T00:36:37.467424Z,"Breaks community rule: ""2. Be kind and respect...",37,"\n{""Rules"": [{""Number"": ""1"", ""Description"": ""A...",{'rules': {1: 'All posts must be related to th...,[2],['Be kind and respectful to one another.'],0,NaN,2
4,20,ani.social,thiccmoe,36835,4939804,Artist obsession with thigh gaps is ridiculous.,Anime characters who have those not-straight l...,2024-06-02T22:18:32.704784Z,2024-06-02T22:58:25.247207Z,Rule 6: No shitting on the art/artist or fans ...,37,"\n{""Rules"": [{""Number"": ""1"", ""Description"": ""P...",{'rules': {1: 'Posts must feature thiccmoe. Th...,[6],"['Positivity only. No shitting on the art, the...",0,NaN,6

In [258]:
modlog_comment_ids = dict()
for (instance, community), group in df.groupby(['instance', 'community_id']):
    modlog_comment_ids[instance, community] = group.comment_id.unique()

In [264]:
df[['instance', 'community_id']].dtypes

instance        object
community_id     int64
dtype: object

In [266]:
len(df)

17254

In [265]:
pd.merge(df, commies[['actor_id', 'instance', 'id']], left_on=['community_id', 'instance'], right_on=['id', 'instance'], how='inner')

,Unnamed: 0,instance,community_name,community_id,comment_id,content,community_description,comment_published,comment_removed,reason,language,exrtacted_rules,extracted_rules_json,rule_numbers,mapped_reasons,is_mass_removed,Unnamed: 0.1,rule,actor_id,id
0,6,ani.social,meta,34,2243845,🤡,Welcome to the AniSocial Lemmy community!\n\nT...,2023-11-07T00:18:02.163076Z,2023-11-07T00:33:39.337517Z,"Breaks community rule: ""2. Be kind and respect...",37,"\n{""Rules"": [{""Number"": ""1"", ""Description"": ""A...",{'rules': {1: 'All posts must be related to th...,[2],['Be kind and respectful to one another.'],0,NaN,2,https://ani.social/c/meta,34
1,7,ani.social,meta,34,2243457,All three regarded instances have admins that ...,Welcome to the AniSocial Lemmy community!\n\nT...,2023-11-06T23:54:25.185884Z,2023-11-07T00:33:57.229908Z,"Breaks community rule: ""2. Be kind and respect...",37,"\n{""Rules"": [{""Number"": ""1"", ""Description"": ""A...",{'rules': {1: 'All posts must be related to th...,[2],['Be kind and respectful to one another.'],0,NaN,2,https://ani.social/c/meta,34
2,8,ani.social,meta,34,2243847,🤡,Welcome to the AniSocial Lemmy community!\n\nT...,2023-11-07T00:18:07.077425Z,2023-11-07T00:34:05.931024Z,"Breaks community rule: ""2. Be kind and respect...",37,"\n{""Rules"": [{""Number"": ""1"", ""Description"": ""A...",{'rules': {1: 'All posts must be related to th...,[2],['Be kind and respectful to one another.'],0,NaN,2,https://ani.social/c/meta,34
3,9,ani.social,meta,34,2243842,Can you please just leave me the fuck alone yo...,Welcome to the AniSocial Lemmy community!\n\nT...,2023-11-07T00:17:23.467802Z,2023-11-07T00:36:37.467424Z,"Breaks community rule: ""2. Be kind and respect...",37,"\n{""Rules"": [{""Number"": ""1"", ""Description"": ""A...",{'rules': {1: 'All posts must be related to th...,[2],['Be kind and respectful to one another.'],0,NaN,2,https://ani.social/c/meta,34
4,20,ani.social,thiccmoe,36835,4939804,Artist obsession with thigh gaps is ridiculous.,Anime characters who have those not-straight l...,2024-06-02T22:18:32.704784Z,2024-06-02T22:58:25.247207Z,Rule 6: No shitting on the art/artist or fans ...,37,"\n{""Rules"": [{""Number"": ""1"", ""Description"": ""P...",{'rules': {1: 'Posts must feature thiccmoe. Th...,[6],"['Positivity only. No shitting on the art, the...",0,NaN,6,https://ani.social/c/thiccmoe,36835
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12923,110435,ttrpg.network,rpg,4,4847780,![zenz](https://www.hexbear.net/pictrs/image/c...,This community is for meaningful discussions o...,2024-01-31T21:53:33.711022Z,2024-02-02T00:14:37.573525Z,Flamewar,37,"\n{""Rules"": [{""Number"": 1, ""Description"": ""Do ...",{'rules': {1: 'Do not distribute pirate conten...,[2],[2],0,67636.0,2,https://ttrpg.network/c/rpg,4
12924,110436,ttrpg.network,rpg,4,4870219,"Oh yeah, Iraq was just a lil oopsie that kille...",This community is for meaningful discussions o...,2024-02-01T22:31:51.573362Z,2024-02-02T00:15:53.096714Z,Flamewar,37,"\n{""Rules"": [{""Number"": 1, ""Description"": ""Do ...",{'rules': {1: 'Do not distribute pirate conten...,[2],[2],0,67637.0,2,https://ttrpg.network/c/rpg,4
12925,110437,ttrpg.network,rpg,4,4867615,你个狗屁 白痴 肏你妈的屄 你二大爷的 蠢豬 你应该为自己感到羞耻 笨蛋Simpleton ...,This community is for meaningful discussions o...,2024-02-01T20:00:05.818559Z,2024-02-02T00:15:58.308254Z,Flamewar,37,"\n{""Rules"": [{""Number"": 1, ""Description"": ""Do ...",{'rules': {1: 'Do not distribute pirate conten...,[2],[2],0,67638.0,2,https://ttrpg.network/c/rpg,4
12926,110438,ttrpg.network,rpg,4,4867134,How much of a racist moron do you need to be t...,This community is for meaningful discussions o...,2024-02-01T19:33:08.242093Z,2024-02-02T00:16:08.709085Z,Flamewar,37,"\n{""Rules"": [{""Number"": 1, ""Description"": ""Do ...",{'rules': {1: 'Do not distribute pirate conten...,[2],[2],0,67639.0,2,https://ttrpg.network/c/rpg,4
12927,110447,ttrpg.network,rpg,4,4866983,"No, I don’t. Iraq was a mistake, and the only ...",This community is for meaningful discussions o...,2024-02-01T19:25:23.264485Z,2024-02-02T00:21:23.015883Z,Flamewar,0,"\n{""Rules"": [{""Number"": 1, ""Description"": ""Do ...",{'rules': {1: 'Do not distribute pirate conten...,[2],[2],0,67648.0,2,https://ttrpg.network/c/rpg,4

In [267]:
for actor_id, g in commies.groupby('actor_id'):
    break

In [273]:

from urllib.parse import urlparse

parsed =urlparse(actor_id)

In [274]:
parsed.netloc

'0xdd.org.ru'

In [275]:
parsed.path[3:].strip('/')

'main'

In [9]:
from ruler.data.load_data import load_data, split
from ruler.models.evaluate_utils import data_to_qa, tokenize

data = load_data('../data/interim/training_Data/')
print(f'date len: {len(data)}')

print(f"data looks like this: \n{data[0]}")
train, test = split(data, random_state=42, strategy='stratified')
print(f"len train: {len(train)}, test: {len(test)}")

import datasets
from functools import partial
custom_tokens = True
custom_rule_tokens = False
qa = list(map(partial(data_to_qa, custom_tokens=custom_tokens, custom_rule_tokens=custom_rule_tokens), train))

examples = datasets.Dataset.from_list(qa)
dataset_qa = examples.train_test_split(test_size=0.2)

from ruler.data.load_data import tokenize
from transformers import BertTokenizerFast, BertForQuestionAnswering


tokenizer = BertTokenizerFast.from_pretrained("bert-base-uncased")
if custom_tokens:
    tokenizer.add_special_tokens(
        {"additional_special_tokens": ["[BOR]", "[EOR]", "[BOC]", "[EOC]"]}
    )
if custom_rule_tokens:
    tokenizer.add_special_tokens(
        {"additional_special_tokens": [f"[RULE{rule_n}]" for rule_n in
                                       range(max(len(entry['rules'] for entry in qa)) + 1)]}
    )
model = BertForQuestionAnswering.from_pretrained("bert-base-uncased")
model.resize_token_embeddings(len(tokenizer))

tokenized_dataset = dataset_qa.map(
    partial(tokenize, tokenizer=tokenizer),
    batched=True,
    remove_columns=dataset_qa["train"].column_names,
    num_proc=4,
)
from ruler.models.grokfast import gradfilter_ema
from torch.utils.data import DataLoader
from evaluate import evaluator
from ruler.models.finetune_QA_manual import format_answers

formatted_eval_dataset = dataset_qa["test"].map(format_answers)

task_evaluator = evaluator("question-answering")



def compute_metrics(pred):
    eval_results = task_evaluator.compute(
        model_or_pipeline=model,
        data=formatted_eval_dataset,
        metric="squad",
        strategy="simple",
        # n_resamples=9999,
        tokenizer=tokenizer,
        squad_v2_format=False,
    )
    return eval_results


dataset = tokenized_dataset.with_format("torch")

train_loader = DataLoader(dataset["train"], batch_size=16, shuffle=True)
eval_loader = DataLoader(dataset["test"], batch_size=16, shuffle=False)

optimizer = torch.optim.AdamW(model.parameters(), lr=2e-6, weight_decay=0.01)
loss = torch.nn.CrossEntropyLoss()
device = 'gpu' if torch.cuda.is_available() else 'cpu'
model = model.to(device)

opt_level = "O1"
# model, optimizer = apex.amp.initialize(bert, optimizer, opt_level=opt_level)

NUM_EPOCHS = 20
GRADIENT_ACC_STEPS = 1
grads = None
alpha = 0.9
lamb = 0.1
# Train Loop
model.train()
for epoch in range(NUM_EPOCHS):
    train_loss = 0
    steps = 0
    for batch in tqdm.tqdm(
            train_loader, desc=f"Epoch {epoch} | Loss: {train_loss / len(train_loader)}"
    ):
        optimizer.zero_grad()
        input_ids = batch["input_ids"].to("cuda")
        attention_mask = batch["attention_mask"].to(device)
        start_positions = batch["start_positions"].to(device)
        end_positions = batch["end_positions"].to(device)
        outputs = model(
            input_ids,
            attention_mask=attention_mask,
            start_positions=start_positions,
            end_positions=end_positions,
        )
        loss_value = loss(outputs["start_logits"], start_positions) + loss(
            outputs["end_logits"], end_positions
        )
        loss_value = loss_value / GRADIENT_ACC_STEPS
        # with apex.amp.scale_loss(loss_value, optimizer) as scaled_loss:
        #     scaled_loss.backward()
        loss_value.backward()

        if steps % GRADIENT_ACC_STEPS == 0:
            optimizer.step()
            grads = gradfilter_ema(model, grads=grads)
        #
        # optimizer.step()
        train_loss += loss_value.item()
        steps += 1

    print(f"Epoch {epoch} Loss: {train_loss / len(train_loader)}")

    # Eval Loop
    model.eval()
    loss_value = 0
    for batch in eval_loader:
        input_ids = batch["input_ids"].to(device)
        attention_mask = batch["attention_mask"].to(device)
        start_positions = batch["start_positions"].to(device)
        end_positions = batch["end_positions"].to(device)

        with torch.no_grad():
            outputs = model(
                input_ids,
                attention_mask=attention_mask,
                start_positions=start_positions,
                end_positions=end_positions,
            )
            loss_value += loss(outputs["start_logits"], start_positions) + loss(
                outputs["end_logits"], end_positions
            )

    print(f"Epoch {epoch} Loss: {loss_value.item() / len(eval_loader)}")

    eval_results = compute_metrics(outputs)
    print(eval_results)
    model.train()
# model.save_pretrained('../../models/d1c0n_model')

date len: 17365
data looks like this:
{'ap_id': 'https://kbin.social/m/pcgaming@lemmy.ca/t/343670/-/comment/1642205', 'applied_rule_n': 1, 'applied_rule_text': 'No Spam or Porn.', 'community': {'actor_id': 'https://lemmy.ca/c/pcgaming', 'description': "For PC gaming news and discussion.\n[PCGamingWiki](https://www.pcgamingwiki.com/wiki/Home)\n\n***Rules:***\n\n0. Be Respectful.\n1. No Spam or Porn.\n2. No Advertising.\n3. No Memes.\n4. No Tech Support.\n5. No questions about buying/building computers.\n6. No game suggestions, friend requests, surveys, or begging.\n7. No Let's Plays, streams, highlight reels/montages, random videos or shorts.\n8. No off-topic posts/comments.\n9. Use the original source, no clickbait titles, no duplicates. \n(Submissions should be from the original source if possible, unless from paywalled or non-english sources.\nIf the title is clickbait or lacks context you may **lightly** edit the title.) ", 'name': 'pcgaming', 'nsfw': False, 'rules': {'0': 'Be Respectful.', '1': 'No Spam or Porn.', '2': 'No Advertising.', '3': 'No Memes.', '4': 'No Tech Support.', '5': 'No questions about buying/building computers.', '6': 'No game suggestions, friend requests, surveys, or begging.', '7': 'No Lets Plays, streams, highlight reels/montages, random videos or shorts.', '8': 'No off-topic posts/comments.', '9': 'Use the original source, no clickbait titles, no duplicates.'}}, 'content': 'friday  <URL>', 'instance': 'l.vidja.social', 'mod_person_id': 1102, 'modlog_id': 133, 'number_of_rules': 10, 'reason': 'spam', 'removed': True}
len train: 13892, test: 3473

In [23]:
with open('../data/external/NormVio/train.jsonl', encoding='utf8') as f, open('../data/external/NormVio/dev.jsonl', encoding='utf8') as ff:
    normvio = list(map(json.loads, f))+list(map(json.loads, ff)) 
normvio[-4]
community_rules = defaultdict(set)
for entry in normvio:
    community_rules[entry['subreddit']].update(entry['rule_texts'].split(' ||| '))
community_rules = {k: {i:j for i, j in enumerate(sorted(v))} for k, v in community_rules.items()}
reverse_community_rules = {k:{j:i for i, j in v.items()} for k, v in community_rules.items()}
normvio = [dict(community=dict(community_id = entry['subreddit'], rules=community_rules[entry['subreddit']]), id = entry['comment_id'], content=entry['final_comment']['tokens'], applied_rule_n = [reverse_community_rules[entry['subreddit']][i] for i in entry['rule_texts'].split(' ||| ')], applied_rule_text=entry['rule_texts'].split(' ||| '), removed=True) for entry in normvio]
normvio[:10]
normvio_linear = list()
cntr = 0
for entry in normvio:
    for rule_n, rule_text in zip(entry.pop('applied_rule_n'), entry.pop('applied_rule_text')):
        entry_ = entry.copy()
        entry['applied_rule_n'] = rule_n
        entry['applied_rule_text'] = rule_text
        entry['id'] = f'{cntr}'
        cntr += 1
        normvio_linear.append(entry)

In [35]:
aegis = pd.read_csv('../data/external/aegis_ai_content_safety_dataset.csv').rename(columns={'label':"applied_rule_n", 'rule_name':'applied_rule_text', 'comment':'content'})
rules = {i['applied_rule_n']: i['applied_rule_text'] for i in
 aegis[['applied_rule_n', 'applied_rule_text']].drop_duplicates().to_dict(orient='records')}
rules
aegis = aegis.to_dict(orient='records')
for idx, i in enumerate(aegis):
    i['id'] = f'aegis_{idx}'
    i['community'] = {'community_id':'aegis_ai_content_safety', 'rules':rules}
    i['removed'] = i['applied_rule_text']=='safe'

In [47]:
len(aegis)

12344

In [48]:
len(normvio_linear)

48344